version: '3'
services:
  postgres:
    image: postgres:14.6
    user: ${uid:-999}:${gid:-999}
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ci
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/postgres

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    user: ${uid:-1000}:${gid:-1000}
    environment:
      #      DEBUG: '*'
      ENVIRONMENT: ci
      VERSION: n/a
      ADDRESS: 0.0.0.0
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ci
      LOG: ""
      PORT: "3000"
      PUBLIC_URL: 'http://api:3000'
      SENTRY_DISABLE: '1'
      TRUST_PROXY: '0'
      CLUSTER_WORKERS: 0
    command: npm run e2e
    depends_on:
      - postgres
