basepath = "."

[[paths]]
reference = "frontend/src/locales/en/messages.json"
l10n = "frontend/src/locales/{locale}/messages.json"

[[paths]]
reference = "frontend/src/locales/en/messages.ftl"
l10n = "frontend/src/locales/{locale}/messages.ftl"
