name: Deployment

on:
  push:
#    branches:
#      - main

jobs:
  deployment:
    needs: docker-build
    runs-on: curlimages/curl:latest
    environment:
      name: production
      url: default-demo_ero-like.tomfun.co
    # url
    # https://stackoverflow.com/questions/67385568/github-actions-how-to-dynamically-set-environment-url-based-on-deployment-step
    steps:
      - name: deploy
        run: |
          export PUBLIC_HTTP_HOST=${CI_ENVIRONMENT_SLUG}-demo_blog.tomfun.co
          export PUBLIC_HTTP_URL=https://$PUBLIC_HTTP_HOST
          export URI_TO_TEST=${PUBLIC_HTTP_URL}/revison-keingeew6eewoh6zangu2eiG7oic9aevaepheew2
          echo "$PUBLIC_HTTP_URL"
          curl --fail -XPOST "https://jenkins.tomfun.co/buildByToken/buildWithParameters?job=ero-like.tomfun.co%2Fdeploy&token=$JENKINS_DEMO_DEPLOY_TOKEN&IMAGE_TAG=$CI_BUILD_REF&PUBLIC_HTTP_HOST=$PUBLIC_HTTP_HOST"
          sleep 20
          curl --fail -XGET $URI_TO_TEST | grep -i "$CI_BUILD_REF" || sleep 20
          curl --fail -XGET $URI_TO_TEST | grep -i "$CI_BUILD_REF" || sleep 10
          curl --fail -XGET $URI_TO_TEST | grep -i "$CI_BUILD_REF"

